    services:
    - name: Google 
        group: Monitoring
        url: https://google.com/
        interval: 1m
        conditions:
        - "[STATUS] == 200"

    - name: Github
        group: Monitoring
        url: https://github.com
        interval: 1m
        conditions:
        - "[STATUS] == 200"
        
    - name: Cloudflare
        group: Monitoring
        url: "icmp://1.1.1.1"
        interval: 1m
        conditions:
        - "[CONNECTED] == true"
