version: '3'
services:
  gatus:
    container_name: gatus
    image: twinproduction/gatus:latest
    ports:
      - "7070:19998"
    volumes:
      - /dockerconf/gatus/config.yaml:/config/
    restart: always
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerconf/portainer_data:/data
    restart: always
